INSERT INTO FuzzyTest (DisplayName) VALUES
  ('The Hitchhikers Guide to the Galaxy'),
  ('Dr. Strangelove or: How I Learned to Stop Worrying'),
  ('The Assassination of Jesse James by the Coward Robert Ford'),
  ('Eternal Sunshine of the Spotless Mind'),
  ('The Lord of the Rings: The Fellowship of the Ring'),
  ('Star Wars: Episode V - The Empire Strikes Back'),
  ('Pirates of the Caribbean: The Curse of the Black Pearl'),
  ('The Chronicles of Narnia: The Lion, the Witch and the Wardrobe'),
  ('Indiana Jones and the Raiders of the Lost Ark'),
  ('To Kill a Mockingbird by Harper Lee'),
  ('One Hundred Years of Solitude by Gabriel Garcia Marquez'),
  ('The Unbearable Lightness of Being'),
  ('Midnight in the Garden of Good and Evil'),
  ('Fear and Loathing in Las Vegas'),
  ('Do Androids Dream of Electric Sheep?'),
  ('The Curious Incident of the Dog in the Night-Time'),
  ('Alexander and the Terrible, Horrible, No Good, Very Bad Day'),
  ('Cloudy with a Chance of Meatballs'),
  ('Fried Green Tomatoes at the Whistle Stop Cafe'),
  ('Zen and the Art of Motorcycle Maintenance'),
  ('The Guernsey Literary and Potato Peel Pie Society'),
  ('Extremely Loud & Incredibly Close'),
  ('Miss Peregrines Home for Peculiar Children'),
  ('Harry Potter and the Prisoner of Azkaban'),
  ('Percy Jackson & The Olympians: The Lightning Thief'),
  ('The Girl with the Dragon Tattoo'),
  ('Tinker Tailor Soldier Spy'),
  ('The Spy Who Came in from the Cold'),
  ('The Man from U.N.C.L.E.'),
  ('Mission: Impossible - Ghost Protocol'),
  ('Quantum of Solace: 007'),
  ('Master and Commander: The Far Side of the World'),
  ('Crouching Tiger, Hidden Dragon'),
  ('House of Flying Daggers'),
  ('Curse of the Golden Flower'),
  ('Memoirs of a Geisha'),
  ('The Last King of Scotland'),
  ('The English Patient'),
  ('Schindlers List: 25th Anniversary'),
  ('Saving Private Ryan'),
  ('All Quiet on the Western Front'),
  ('The Bridge on the River Kwai'),
  ('Lawrence of Arabia (Restored Version)'),
  ('Butch Cassidy and the Sundance Kid'),
  ('The Good, the Bad and the Ugly'),
  ('Once Upon a Time in the West'),
  ('A Fistful of Dollars'),
  ('For a Few Dollars More'),
  ('The Magnificent Seven'),
  ('Three Billboards Outside Ebbing, Missouri'),
  ('Birdman or (The Unexpected Virtue of Ignorance)'),
  ('Everything Everywhere All At Once'),
  ('Guardians of the Galaxy Vol. 3'),
  ('Spider-Man: Across the Spider-Verse'),
  ('Captain America: The Winter Soldier'),
  ('Avengers: Age of Ultron'),
  ('Thor: Ragnarok - Marvel Studios'),
  ('Black Panther: Wakanda Forever'),
  ('X-Men: Days of Future Past'),
  ('Fantastic Beasts and Where to Find Them'),
  ('Alice in Wonderland: Through the Looking Glass'),
  ('Charlie and the Chocolate Factory'),
  ('James and the Giant Peach'),
  ('The BFG (Big Friendly Giant)'),
  ('Matilda by Roald Dahl'),
  ('Where the Wild Things Are'),
  ('The Very Hungry Caterpillar'),
  ('Green Eggs and Ham by Dr. Seuss'),
  ('How the Grinch Stole Christmas!'),
  ('The Cat in the Hat Comes Back'),
  ('Horton Hears a Who!'),
  ('Winnie-the-Pooh and the Blustery Day'),
  ('The House at Pooh Corner'),
  ('Paddington Bear: A Bear Called Paddington'),
  ('The Tale of Peter Rabbit'),
  ('The Wind in the Willows'),
  ('The Velveteen Rabbit'),
  ('Charlotte’s Web by E.B. White'),
  ('Stuart Little by E.B. White'),
  ('The Secret Garden by Frances Hodgson Burnett'),
  ('A Little Princess by Frances Hodgson Burnett'),
  ('Anne of Green Gables'),
  ('Little Women by Louisa May Alcott'),
  ('The Adventures of Tom Sawyer'),
  ('The Adventures of Huckleberry Finn'),
  ('Around the World in Eighty Days'),
  ('Twenty Thousand Leagues Under the Sea'),
  ('Journey to the Center of the Earth'),
  ('The Count of Monte Cristo'),
  ('The Three Musketeers'),
  ('The Hunchback of Notre Dame'),
  ('Les Misérables by Victor Hugo'),
  ('The Phantom of the Opera'),
  ('Frankenstein; or, The Modern Prometheus'),
  ('The Strange Case of Dr Jekyll and Mr Hyde'),
  ('Dracula by Bram Stoker'),
  ('The Picture of Dorian Gray'),
  ('Great Expectations by Charles Dickens'),
  ('A Tale of Two Cities'),
  ('David Copperfield by Charles Dickens');
